Feat/challenge 3 loops conditionals
adrianagrd/JavaScript-foundations-challenge-1 pull request #4
Opened 2023-11-04 12:11 UTC by adrianagrd

2023-11-05 18:11 UTC, tictools requested changes

2023-11-05 18:11 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/.gitignore
⚠️ FIX: move this file to root level

2023-11-05 18:11 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/.prettierignore
⚠️ FIX: move this file to root level

2023-11-05 18:11 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/package-lock.json
⚠️ FIX: move this file to root level

2023-11-05 18:11 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/package.json
⚠️ FIX: move this file to root level

2023-11-05 18:11 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/README.md
`README.md` should live at root level. In fact, it is already there (you can check it if you move to project root)

⚠️ FIX: remove this file from this folder

2023-11-05 18:11 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/index.js
⚠️ FIX: remove file

2023-11-05 18:11 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/loops-conditionals/conditionals/exercise_00.js
> +if (animal === "cat") {
⚠️ FIX: Change animal to different values to make sure it works in all cases

2023-11-05 18:11 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/loops-conditionals/loops/exercise_00.js
> +print("Select an option: ");
This is the output of your script...
```
ReferenceError: print is not defined
```

...have you tested it before pushing? 🤔

⚠️ FIX: spot the 🐛 and fix it.

2023-11-05 18:11 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/loops-conditionals/loops/exercise_00.js
> +for (let i = 10; i <= 40; i++) {
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

2023-11-05 18:11 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/loops-conditionals/loops/exercise_02.js
> +for (let i = 1; i <= 100; i++) {
You should take in account what `i` variable is storing. Is this variable referring to any index in this case, or a number?

⚠️ FIX: rename properly `i` variable

2023-11-05 18:11 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/loops-conditionals/while/exercise_01.js
> +print("Select an option: ");
This is the output of your script...
```
ReferenceError: print is not defined
```

...have you tested it before pushing? 🤔

⚠️ FIX: spot the 🐛 and fix it

2023-11-05 18:11 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/loops-conditionals/while/exercise_01.js
> +let i = 10;
You should take in account what `i` variable is storing. Is this variable referring to any index in this case?

⚠️ FIX: rename properly `i` variable

2023-11-05 18:11 UTC, tictools commented on challenge_03_loops-conditionals/03_JavaScript_foundations/loops-conditionals/while/exercise_02.js
> +let i = 1;
You should take in account what `i` variable is storing. Is this variable referring to any index in this case?

⚠️ FIX: rename properly `i` variable

2023-11-12 17:47 UTC, tictools approved these changes

2023-11-12 20:27 UTC, aalvar0 approved these changes

2023-11-13 17:45 UTC, merged